#pragma once

#include <vector>
#include <memory>

#include "../Math/random.h"
#include "../WaveFunctions/wavefunction.h"
#include "../particle.h"

class MonteCarlo
{
    public:
        MonteCarlo(std::unique_ptr<class Random> rng);
        // Use the default deconstructor generated by the compiler
        virtual ~MonteCarlo() = default;
    
        virtual bool step(
                double stepLength,
                class WaveFunction& waveFunction,
                std::vector<std::unique_ptr<class Particle>>& particles) = 0;
    
    protected:
        std::unique_ptr<class Random> m_rng;
};