#pragma once

#include <cassert>
#include <memory>
#include <vector>

#include "../system.h"
#include "../particle.h"


class WaveFunction
{
    public:
        // Use the default deconstructor generated by the compiler
        virtual ~WaveFunction() = default;
    
        int getNumberOfParameters() { return m_numberOfParameters; }
        const std::vector<double>& getParameters() { return m_parameters; }

        double r_squared(std::vector<std::unique_ptr<class Particle>>& particles, int part_index);
        double r_ij(std::vector<std::unique_ptr<class Particle>>& particles, int i, int j);
        int BetaIndex(int i, int j);
        double a_ij(int i, int j);
        double GreensFunctionRatio(std::vector<double>& Rnew, std::vector<double>& Rold, 
                                    double dt, std::vector<double>& Fold, std::vector<double>& Fnew);

        virtual double evaluate(std::vector<std::unique_ptr<class Particle>>& particles) = 0;
        virtual double computeDoubleDerivative(std::vector<std::unique_ptr<class Particle>>& particles) = 0;
        virtual std::vector<double> quantumForce(std::vector<std::unique_ptr<class Particle>>& particles, int i) = 0;
    
    protected:
        int m_numberOfParameters = 0;
        std::vector<double> m_parameters = std::vector<double>();
        int m_particles = 0;
        int m_mode = 0;
        double m_omega = 0;
        double m_sqrt_om = 0;
};