#pragma once

#include <cassert>
#include <memory>
#include <vector>

#include "../system.h"
#include "../particle.h"


class WaveFunction
{
    public:
        // Use the default deconstructor generated by the compiler
        virtual ~WaveFunction() = default;
    
        int getNumberOfParameters() { return m_numberOfParameters; }
        const std::vector<double>& getParameters() { return m_parameters; }
        virtual double r_squared(std::vector<std::unique_ptr<class Particle>>& particles, int part_index) = 0;
        virtual double r_ij(std::vector<std::unique_ptr<class Particle>>& particles, int i, int j) = 0;
        virtual double evaluate(std::vector<std::unique_ptr<class Particle>>& particles) = 0;
        virtual double computeDoubleDerivative(std::vector<std::unique_ptr<class Particle>>& particles) = 0;
    
    protected:
        int m_numberOfParameters = 0;
        std::vector<double> m_parameters = std::vector<double>();
        int m_particles = 0;
        int m_mode = 0;
};